CREATE TABLE taxonomy_release (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version VARCHAR(120) NOT NULL UNIQUE,
    source_revision VARCHAR(160) NOT NULL,
    source_url VARCHAR(500) NOT NULL,
    checksum_sha256 CHAR(64) NOT NULL UNIQUE,
    imported_at TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(16) NOT NULL CHECK (status IN ('staged', 'active', 'retired', 'failed')),
    entry_count INTEGER NOT NULL DEFAULT 0 CHECK (entry_count >= 0),
    label_count INTEGER NOT NULL DEFAULT 0 CHECK (label_count >= 0),
    edge_count INTEGER NOT NULL DEFAULT 0 CHECK (edge_count >= 0),
    activated_at TIMESTAMP WITH TIME ZONE NULL
);

CREATE TABLE ingredient_taxon (
    release_id BIGINT NOT NULL REFERENCES taxonomy_release(id) ON DELETE CASCADE,
    taxonomy_id VARCHAR(300) NOT NULL,
    PRIMARY KEY (release_id, taxonomy_id)
);

CREATE TABLE ingredient_label (
    release_id BIGINT NOT NULL,
    taxonomy_id VARCHAR(300) NOT NULL,
    locale VARCHAR(2) NOT NULL CHECK (locale IN ('pl', 'en')),
    kind VARCHAR(16) NOT NULL CHECK (kind IN ('canonical', 'synonym')),
    label VARCHAR(500) NOT NULL,
    normalized_label VARCHAR(500) NOT NULL,
    PRIMARY KEY (release_id, taxonomy_id, locale, kind, normalized_label),
    FOREIGN KEY (release_id, taxonomy_id)
        REFERENCES ingredient_taxon(release_id, taxonomy_id) ON DELETE CASCADE
);

CREATE INDEX ingredient_label_search_idx
    ON ingredient_label(release_id, locale, normalized_label);

CREATE TABLE ingredient_parent (
    release_id BIGINT NOT NULL,
    child_id VARCHAR(300) NOT NULL,
    parent_id VARCHAR(300) NOT NULL,
    PRIMARY KEY (release_id, child_id, parent_id),
    CHECK (child_id <> parent_id),
    FOREIGN KEY (release_id, child_id)
        REFERENCES ingredient_taxon(release_id, taxonomy_id) ON DELETE CASCADE,
    FOREIGN KEY (release_id, parent_id)
        REFERENCES ingredient_taxon(release_id, taxonomy_id) ON DELETE CASCADE
);

CREATE INDEX ingredient_parent_parent_idx
    ON ingredient_parent(release_id, parent_id);

CREATE TABLE active_taxonomy_release (
    singleton_key SMALLINT PRIMARY KEY CHECK (singleton_key = 1),
    release_id BIGINT NOT NULL UNIQUE REFERENCES taxonomy_release(id)
);
